# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_PUBLIC_URL'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_PUBLIC_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_PUBLIC_URL'] %>