default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: postgresql://postgres:FyfiIrDdScmnXmGQrmqOHgRpZFXSnaCX@crossover.proxy.rlwy.net:16243/railway

test:
  <<: *default
  url: postgresql://postgres:FyfiIrDdScmnXmGQrmqOHgRpZFXSnaCX@crossover.proxy.rlwy.net:16243/railway

production:
  <<: *default
  url: postgresql://postgres:FyfiIrDdScmnXmGQrmqOHgRpZFXSnaCX@crossover.proxy.rlwy.net:16243/railway
